name: flutter_tanstack_query
description: A powerful data fetching and state management package for Flutter inspired by TanStack Query (React Query). Features automatic caching, background updates, offline support, and optimistic UI updates.
version: 0.0.1+3
homepage: https://github.com/Haraprosad/flutter_tanstack_query
repository: https://github.com/Haraprosad/flutter_tanstack_query
issue_tracker: https://github.com/Haraprosad/flutter_tanstack_query/issues
documentation: https://github.com/Haraprosad/flutter_tanstack_query#readme

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #######################################################
  # For network requests, can be swapped out by user
  #######################################################
  dio: ^5.8.0+1

  #########################################################
  # For network status detection
  #########################################################
  connectivity_plus: ^6.1.4

  #########################################################
  # For persistent caching
  #########################################################
  hive: ^2.2.3

  #########################################################
  # For specific Hive integration with Flutter
  #########################################################
  hive_flutter: ^1.1.0

  #########################################################
  # To get application document directory for Hive
  #########################################################
  path_provider: ^2.1.5

  #########################################################
  # For @immutable annotation
  #########################################################
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  #########################################################
  # For generating Hive adapters
  #########################################################
  hive_generator: ^2.0.1

  #########################################################
  # For running code generators
  #########################################################
  build_runner: ^2.5.4

  #########################################################
  # For testing (dev dependency)
  #########################################################
  mockito: ^5.4.5
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
